wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.19.0
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.16
    start_time: 1749644992
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      3:
      - 4
      - 13
      - 16
      - 23
      4: 3.10.16
      5: 0.19.0
      6: 4.40.1
      8:
      - 5
      - 9
batch_size:
  desc: null
  value: 512
debug:
  desc: null
  value: false
epochs:
  desc: null
  value: 10
grad_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
preprocessed_data:
  desc: null
  value: true
