# need 4 gpus

project: coconut
save_path: ckpt
name: gsm-coconut

only_eval: False


coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: /data2/xxw_data/projects/LLM/coconut/data/gsm_train.json
val_path: /data2/xxw_data/projects/LLM/coconut/data/gsm_valid.json
reset_optimizer: True
batch_size_training: 64
debug: True
gradient_accumulation_steps: 1
num_epochs: 30
lr: !!float "0.0001"
weight_decay: 0.01